time python3.10 main.py --task 0\
                      --selection-function z1\
                      --n-bits-selection-function 4\
                      --target-key k1\
                      --first-subkey-index 6 16 24 34 42 52 60\
                      --n-rank 8\
                      --n-traces 10000\
                      --n-repetition 1\
                      --space 10000\
                      --path-to-traces ../armv6/traces0\
                      --start-sample 0\
                      --end-sample 1000\
                      --step 250\
                      --data-type float64\
                      --path-to-nonces ../armv6/nonces0.npy\
                      --path-to-checkpoints ../armv6/checkpoints0\