time python3.10 main.py --task 0\
                     --selection-function z0\
                     --n-bits-selection-function 1\
                     --target-key k0\
                     --first-subkey-index 1 2 5 8 11 12 15 18 19 22 25 28 29 32 35 39 42 45 49 52 55 59 62\
                     --n-rank 3\
                     --n-traces 10000\
                     --n-repetition 1\
                     --space 10000\
                     --path-to-traces ../data/traces0\
                     --start-sample 0\
                     --end-sample 1000\
                     --step 250\
                     --data-type float64\
                     --path-to-nonces ../data/nonces0.npy\
                     --path-to-checkpoints ../outputs/checkpoints0